include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_function_literals_in_foreach_calls: true
    avoid_field_initializers_in_const_classes: true
    avoid_redundant_argument_values: true
    avoid_types_on_closure_parameters: true
    avoid_slow_async_io: true
    avoid_void_async: true
    #    avoid_dynamic_calls: true
    cascade_invocations: true
    #    discarded_futures: true
    directives_ordering: true
    #    flutter_style_todos: true
    file_names: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    #    prefer_expression_function_bodies: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    prefer_int_literals: true
    prefer_null_aware_method_calls: true
    prefer_null_aware_operators: true
    prefer_relative_imports: true
    type_annotate_public_apis: true
    #    unawaited_futures: true
    unnecessary_await_in_return: true
    unnecessary_breaks: true
    unnecessary_lambdas: true
    unnecessary_parenthesis: true
    use_build_context_synchronously: true
    use_colored_box: true
    use_decorated_box: true
    use_enums: true
    use_full_hex_values_for_flutter_colors: true
    use_function_type_syntax_for_parameters: true
    use_if_null_to_convert_nulls_to_bools: true
    use_is_even_rather_than_modulo: true
    use_key_in_widget_constructors: true
    use_named_constants: true
    #    use_null_aware_elements: true
    use_raw_strings: true
    use_rethrow_when_possible: true
    use_string_buffers: true
    use_super_parameters: true
    use_to_and_as_if_applicable: true
    use_truncating_division: true
    valid_regexps: true
